apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: fleet-control-plane
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  generators:
  - clusters:
      selector:
        matchLabels:
          tenant: control-plane
  template:
    metadata:
      name: fleet-control-plane
    spec:
      project: default
      source:
        repoURL: '{{metadata.annotations.fleet_repo_url}}'
        path: '{{metadata.annotations.fleet_repo_basepath}}{{metadata.annotations.fleet_repo_path}}' ##bootstrap/fleet
        targetRevision: '{{metadata.annotations.fleet_repo_revision}}'
        directory:
          recurse: true
          exclude: exclude/*
      destination:
        namespace: 'argocd'
        name: '{{name}}'
      syncPolicy:
        automated: {}
